package com.artixtise.richdialer.application

object ErrorMessage {
    val PHONENUMBER_IS_EMPTY="Please Enter Phone Number"
    val PHONENUMBER_IS_INVALID="Please Enter Valid Phone Number"
    val INTERNET_CONNECTION_ERROR="Please Connect To Internet Connection"
    val THEME_ERROR="Theme Already implemented"
    val ENTER_OTP="Please Enter OTP"
    val INVALID_OTP="Please Enter Valid OTP"
    val PLEASE_WAIT="Please wait"
    val OTP_VERIFICATION_FAILED="Entered OTP is Incorrect"
    val OTP_VERIFICATION_SUCCESSFULLY="OTP is Successfully Verified "
    val ADD_TO_FAV_SUCCESSFULLY="this Contact is now Your Favourite Contact"
    val ADD_TO_FAV_FAILURE="this Contact is Remove from Favourite Contact"
    val CONTACT_SAVED="Contact Saved Successfully"
    val CALL_PERMISSION="Need Call Permission"
    val LOCATION_SERVICE_PERMISSION="Require Location Permission from Setting"
    val USER_REGISTERED="User Register Successfully"
    val USER_SAVED="User Data Saved Successfully"
    val OTHER_USER_DATA="success"
    val SAVE_RICH_CALL_DATA="Successfully send."
    val NOT_AVAILABLE__RICH_CALL_DATA="Rich Call not Available for this Contact"
    val ERROR="error"
    val ERROR_ON_GETTING_USER="User Not Found"
    val GIF_UPLODED="Gif Uploaded Successfully"
    val SOME_THIING_WRONG="Something went wrong"
}